export const environment = {
  production: true,
  domain: "yolo96bet.com",
  admindomain: "https://admin.easybet24.com/storage/app/public/",
  port: "",
  apipath: "/api/v5/",
  apipath2: "/api/",
  chatsupport: "",
  showMarketInfo: true,
  loginPageType: 1,
  websiteName: "yolo96bet",
  supportSystemAvailable: false,
  xpgSideMenuAvailable: false,
  ezugiSideMenuAvailable: false,
  lotusSideMenuAvailable: false,
  casinoSideMenuAvaliable: false,
  oddsBlinkAvailable: true,
  hideExtraOdds: false,
  backTitleName: "Back",
  layTitleName: "Lay",
};
